FROM python:3.7-slim

RUN apt-get update && apt-get install -y \
    gcc \
    nmap \
    libpq-dev \
    && apt-get clean

RUN mkdir /app
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip3 install -r ./requirements.txt

RUN mkdir ./api
COPY ./api ./api
WORKDIR /app/api/

CMD ["python3", "./server.py"]