FROM python:3.6

RUN apt-get update
RUN apt-get install nmap -y
#=7.70 -y

RUN mkdir /app
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip3 install -r ./requirements.txt

RUN mkdir ./api
COPY ./api ./api
WORKDIR /app/api/

CMD ["python3", "./server.py"]